### PR TITLE
Ensure a non-zero exit status code when build has errors 

### PR DESCRIPTION
**Pull request by nddery**
## Description

Ensure `init()` always return a `Promise`. This prevents the issue described in https://github.com/react-static/react-static/issues/1260.

Since `init()` returns a `Promise`, it would need to be awaited for. However, we can't `await` at the top-level, so we would have needed to wrap the `try/catch` in an `async` function for it to work, like so:

Example of awaiting:

```js
async function main() {
  try {
    await init()
  } catch(e) {
    console.trace(e)
    process.exit(1)
  }
}
main()
``` 

This just seem overly complex, so I went for the `catch` as it's nicer than wrapping the `try/catch`.

## Changes/Tasks

- [X] Changed code

- `yarn build` with an error thrown, exit status is 1.
- `yarn build` with no error thrown, exit status is 0.
- `yarn react-static` logs the usage info, exit status is 0, no error logged

I have not added tests yet, would love some, will look into it!

## Motivation and Context

Closes/Fixes https://github.com/react-static/react-static/issues/1450

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have updated the documentation accordingly
- [ ] I have updated the CHANGELOG with a summary of my changes
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by nddery** [comment]
@SleeplessByte any idea on how we could add tests around `bin/react-static`, and if that is worth it (especially with RS8 changing things up) ?

**Comment by SleeplessByte** [comment]
It's possible to call the bin/xxx programmatically. Might be worth it. I wouldn't do it for now; because RS7 is pretty complex :(

**Comment by nddery** [comment]
Yeah that make sense. I guess I was mostly wondering of ways to provide the executable with the mocks and whatnot (templates). I guess that's the same conclusion than you've arrived at in https://github.com/react-static/react-static/pull/1383#issuecomment-588544456.

**Comment by SleeplessByte** [comment]
(You got merge permissions btw)

**Comment by nddery** [comment]
Haha I do! Do you feel like this warrant a 7.4.1 release ?

**Comment by SleeplessByte** [comment]
If you need it, sure. But I think you also run a local copy right?

**Comment by nddery** [comment]
I run a local copy for development but we do run the one from NPM when building during deploys. I can take care of making a release PR if you'd like (unclear to me exactly what the steps are), and then there would only be the tags to push to NPM or something ?

**Comment by nddery** [comment]
@SleeplessByte any thoughts on this ? I don't think I can push a release myself but probably can make a PR for it (although, I'm not sure of what command to run for this).

**Comment by SleeplessByte** [comment]
I forgot about this! You can create the release PR if you'd like, I'll merge and deploy then. I'll document which commands I run to release at some point. 

85 hour work weeks coming to an end in about 1 month, then I can focus on getting some sponsorships for React Static and build v8.

**Comment by nddery** [comment]
Thats a lot of work hours -- take care of yourself too! I'll open a PR for a release.

**Pull request merged**
