### PR TITLE
[Feature] Added Nested XML Object support for Sitemap

### PR DESCRIPTION
**Pull request by ptariche**
Updated react-static-plugin-sitemap to take into account nested objects for xml params like image:image and others

## Description

Added the ability for nested objects for further rich xml injection that is rich for SEO in regards to sitemaps being generated.

## Changes/Tasks

- [x] Changed code

## Motivation and Context

Ideally there should be a solution to incorporate this issue as key object pairs -- nested to the appropriate needs for all the variable sitemap xml tags needed. Image tags greatly improve SEO for websites, especially on Google

## Screenshots (if appropriate):

74190875-e6453a00-4c07-11ea-8458-32203e24d5a3

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have updated the documentation accordingly
- [x] I have updated the CHANGELOG with a summary of my changes
- [x] My changes have tests around them

### CODE REVIEW

**Comment by ptariche** [comment]
#1380 as ref for possible change.

**Comment by SleeplessByte** [comment]
Did you close this on purpose?

**Comment by ptariche** [comment]
@SleeplessByte I'm not sure what the PR procedure is, but the build failed so I figured I'd let you all add. I was unable to get my jest test to work within the package after added it within the test directory. I did test locally.

**Comment by SleeplessByte** [comment]
The failed build also says why it failed (and this _should_ have failed locally as well):
```text
 › 3 snapshots failed from 1 test suite. Inspect your code changes or 
 › run `yarn run unitTest -u` to update them.
```

You can find the failed tests here: https://travis-ci.com/react-static/react-static/builds/148334413.

Normally someone wouldn't close a PR if a build fails, but instead we can try together to fix it so it can be merged.

**Comment by ptariche** [comment]
@SleeplessByte  ^ I hope this is everything you all were looking for to make this feature ready.

**Comment by ptariche** [comment]
Video (https://support.google.com/webmasters/answer/80471) and News (https://support.google.com/webmasters/answer/9606710?hl=en&ref_topic=4581190) can easily be added as well by adding to the xmlns

**Comment by ptariche** [comment]
Just wanted to follow-up on this @SleeplessByte

**Comment by SleeplessByte** [comment]
Nice. We'll look into merging this after #1375

**Comment by SleeplessByte** [comment]
Just wanted to let you know that this is basically good to go, but we're _still_ working on fixing minor edge cases, especially for windows in that release branch. Sorry for the hold-up!

**Comment by ptariche** [comment]
👍

**Comment by ptariche** [comment]
Just checking in on this.

**Pull request merged**
