### PR TITLE
update plugin for react-jss v10+

### PR DESCRIPTION
**Pull request by yanick**
Basically change the imports as mentioned in #1266

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Can you merge in master?

**Comment by yanick** [comment]
Rebased to master!

**Comment by SleeplessByte** [comment]
Sweet. This seems to work!

Can you also add it to the CHANGELOG.md? Then I'll merge it in.

**Comment by yanick** [comment]
Changelog updated!

**Pull request merged**
