### PR TITLE
Add frontmatter support to the MDX plugin

### LINKED ISSUE #1336: Frontmatter support in mdx plugin
I would like to be able to use frontmatter in mdx files.

**Describe the solution you'd like**
That I can do this:
```
import AwesomeContent, { frontMatter } from './awesome-content.mdx'
```
and have `frontMatter` equal `{ title: 'Awesome!' }` if `awesome-content.mdx` starts with this:

```
---
title: Awesome!
---
```

**Describe alternatives you've considered**
The only alternative I can see now, is placing a JSON file next to the mdx file with the data I need. I have tried writing a react-static plugin to handle this, but it doesn't seem to be possible - it must be done in the mdx plugin.

### PR DESCRIPTION
**Pull request by chucklam**
## Description

The plugin can now pull out frontmatter metadata when processing markdown files.

To demonstrate, create a basic `react-static` site (`react-static create --template basic`). Install this plugin and add the following to `static.config.js`'s `plugins` array:
```javascript
    [
      'react-static-plugin-mdx',
      { parseFrontMatter: true }
    ],
```
Create the following markdown file in `src/markdown/about.md`
```markdown
---
title: Awesome!
---
# A new 'About' page
```
Change the template's `about.js` to
```javascript
import about, { frontMatter } from '../markdown/about.md';
console.log(frontMatter); // Will output { title: 'Awesome!' }

export default about; // A React component for (<h1>A new 'About' page</h1>)
```
You should see a new 'About' page and the developer console will output the frontmatter.

To be backward compatible, frontmatter support is disabled by default, thus the need to enable it manually with `{ parseFrontMatter: true }`.

## Changes/Tasks

The MDX plugin works by [adding](https://mdxjs.com/getting-started/webpack) `@mdx-js/loader` before the `babel` loader in `webpack`. I'm adding a custom frontmatter loader ahead of the MDX loader to extract the frontmatter first. The code follows closely the [example in the MDX documentation](https://mdxjs.com/guides/custom-loader).

- [x] Changed code

## Motivation and Context

Close #1336 
It's very common to have frontmatter in markdown documents, therefore the MDX plugin should support it.

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have updated the documentation accordingly
- [ ] I have updated the CHANGELOG with a summary of my changes
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by SleeplessByte** [comment]
This is looking great so far!

Can you make sure you run the format, build (to test) and add an entry to CHANGELOG.md ?

**Comment by chucklam** [comment]
@SleeplessByte Added formatting, build/test, and line in CHANGELOG.

BTW what's the timeframe for the next release? I want to package up my own project for a collaborator. I'm deciding between waiting for the next release or if I should include a copy of the plugin.

Thanks!

**Comment by SleeplessByte** [comment]
Uh. I can try to do a release this week! If time allows, I will! Otherwise packaging it up yourself and vendoring it might not be the worst of ideas :)

**Comment by aloxe** [comment]
Why did I just decide to follow the documentation yesterday not understanding why frontmatter was not retrieved. Thanks @chucklam and @SleeplessByte for this update. I think I'll now wait for the package.

**Comment by docrinehart** [comment]
Doesn't seem like this plugin is getting published out with the same version as react-static...

Package json is still listed at 7.2.2, and that's the latest I get with npm install.

**Comment by SleeplessByte** [comment]
> UPDATE: Actually, it doesn't seem like there's been a publish at all that would contain the frontMatter changes. That said, not sure if the versioning is still an issue.

I haven't published (yet) since this was merged.

**Comment by SleeplessByte** [comment]
Thank you for your contribution @chucklam. It was [just released](https://github.com/react-static/react-static/releases/tag/v7.5.0).

**Pull request merged**
