### PR TITLE
Fix mismatched chunk names

### PR DESCRIPTION
**Pull request by chucklam**
# Mismatched chunk names between bundle and export

## Description
When the output directory (`config.paths.dist`) is changed to somewhere outside the working directory, there's a lot of warning messages during build.

To reproduce the problem:
```
react-static create --template basic
```

Run `yarn build` right away and it works fine.

Add to `static.config.js` a `paths.dist` property that points somewhere outside the working directory.
```
export default {
  paths: {
    dist: '/tmp/react-static'
  },
  getRoutes: ...,
  plugins: ...,
}
```

Run `yarn build` again and it gives a bunch of warnings.
```
Exporting HTML across 4 threads...
[FLUSH CHUNKS]: Unable to find __react_static_root__/src/pages/404 in Webpack chunks. Please check usage of Babel plugin.
[FLUSH CHUNKS]: Unable to find __react_static_root__/src/containers/Post in Webpack chunks. Please check usage of Babel plugin.
[FLUSH CHUNKS]: Unable to find __react_static_root__/src/pages/index in Webpack chunks. Please check usage of Babel plugin.
[FLUSH CHUNKS]: Unable to find __react_static_root__/src/containers/Post in Webpack chunks. Please check usage of Babel plugin.
[FLUSH CHUNKS]: Unable to find __react_static_root__/src/containers/Post in Webpack chunks. Please check usage of Babel plugin.
[FLUSH CHUNKS]: Unable to find __react_static_root__/src/containers/Post in Webpack chunks. Please check usage of Babel plugin.
[FLUSH CHUNKS]: Unable to find __react_static_root__/src/containers/Post in Webpack chunks. Please check usage of Babel plugin.
[FLUSH CHUNKS]: Unable to find __react_static_root__/src/containers/Post in Webpack chunks. Please check usage of Babel plugin.
...
```

## Motivation and Context

https://github.com/react-static/react-static/issues/1211 has an ongoing discussion on this.

In the bundling phase, templates are generated. And if `config.paths.dist` is different from "ROOT", the webpack chunk name for each template is [computed and assigned](https://github.com/react-static/react-static/blob/master/packages/react-static/src/static/generateTemplates.js#L36) with `chunkNameFromFile()`.

In the export phase, it's doing some pre-rendering magic with `react-universal-component` that I don't understand... But at one point it also references chunk names, and in the same case when `config.paths.dist` is different from "ROOT", it [calls](https://github.com/react-static/react-static/blob/master/packages/react-static/src/static/exportRoute.js#L150) `absoluteToRelativeChunkName()` to recompute the chunk name and truncate any prefix. There it looks asymmetric that `chunkNameFromFile()` is called when there's a prefix to truncate ([L36](https://github.com/react-static/react-static/blob/master/packages/react-static/src/utils/chunkBuilder.js#L36)) but not when there isn't ([L31](https://github.com/react-static/react-static/blob/master/packages/react-static/src/utils/chunkBuilder.js#L31)). I assume that's an unintentional omission as adding `chunkNameFromFile()` back in also fixes the problem above.

### CODE REVIEW

**Comment by SleeplessByte** [comment]
I think you're right.

@nddery if you have time, can you confirm?

**Comment by nddery** [comment]
@SleeplessByte that all make sense to me.

@chucklam thanks for looking into this! Might be worth adding a test for this ?

**Comment by chucklam** [comment]
Tests added.

After looking at the existing tests, I also decided to call `chunkNameFromFile()` earlier in the code. It preserves the existing behaviors and makes `chunkName` and `pathPrefix` look more comparable.

**Review by SleeplessByte — APPROVED** [review]
Great. 

Can you add the entry to CHANGELOG.md?

**Comment by SleeplessByte** [comment]
Looking great!

**Comment by alqamabinsadiq** [comment]
@chucklam  I added your suggested fix in my react-static version, and it looks like it is not working. I still see the [FLUSH CHUNKS] error.

**Comment by chucklam** [comment]
@alqamabinsadiq Actually I did it your hacky way in the beginning too :rofl: I went with the "proper" way only after I isolated the problem.

Based on your description, I suspect you didn't run `yarn build` in the `node_modules/react-static/` directory after making the changes. The actual code is being picked up at `node_modules/react-static/lib/` not `node_modules/react-static/src/`.

If that's not the problem, can you log `ROOT`, `pathPrefix`, and `chunkName` (both before and after `chunkNameFromFile`)? There may be cases I haven't tested.

**Comment by alqamabinsadiq** [comment]
@chucklam Strange thing happened to me. I ran `npm install` again after deleting the node_modules, and it worked for me without even adding the above fix you mentioned. I can no longer see [FLUSH CHUNKS] errors. The main bug which I am facing is the reloading of content. After refreshing the page, my page is being rerendered. 

Check this out: https://experience-1605206018346.elphie.io/alqama/

Check, I think something is wrong with the routes. Just so you know the top navigation bar is top of routes that's why it is not re-rendering it. I am also prefetching the other routes info as you can see in the network tab.

**Comment by SleeplessByte** [comment]
This was also included in 7.5.0.

**Pull request merged**
