### PR TITLE
Use 'overrideBrowserslist' option instead of 'browsers' in autoprefixer

### PR DESCRIPTION
**Pull request by jxom**
## Description

As of [autoprefixer@9.6.0](https://github.com/postcss/autoprefixer/releases/tag/9.6.0), autoprefixer recommends to use a `.browserslistrc` file or a `browserslist` attribute in package.json. Currently, if you try to run or build a react-static project, it will [warn you and tell you to do the above (#1220)](https://github.com/nozzle/react-static/issues/1220).

If we remove the `browsers` option in the autoprefixer, this will introduce a breaking change as consumers will need to create a browserslist config. For now, I have renamed the `browsers` option to `overrideBrowserslist` to avoid any breaking changes, and in the next major React Static release, maybe we remove this option in favour of the browserslist config file. Keen to hear your thoughts!

## Changes/Tasks

- [x] Rename `browsers` option to `overrideBrowserslist` in the autoprefixer config.
- [x] Update autoprefixer to ^9.6.0

## Motivation and Context

Solves #1220.

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have updated the documentation accordingly
- [ ] I have updated the CHANGELOG with a summary of my changes
- [ ] My changes have tests around them

### CODE REVIEW

**Comment by digitalkaoz** [comment]
im assuming they have a hierarchy like babel? Then i would first try to include the config file from the users workspace, otherwise we load the default one from react-static?

**Comment by cortopy** [comment]
`overrideBrowserslist` feels very cumbersome to me (as a newcomer). I want to use my own browserlist and with this change, I would have to reconfigure every webpack plugin that uses the list in order to "override the override"

**Comment by sw-yx** [comment]
anyone one to send in an alternative PR?

**Comment by jxom** [comment]
Fair call. I've committed an update which adds browserslist config to react-static to fallback on instead - allowing the user to specify their own browserslist config.

**Comment by digitalkaoz** [comment]
@jxcom im not sure your latest change is correct. I cant see the fallback scenario

**Comment by sw-yx** [comment]
hi everyone! thanks for your PR! there is now a call for maintainers of React Static, please weigh in here: https://github.com/nozzle/react-static/issues/1259

**Comment by SleeplessByte** [comment]
Closed in favour of #1283 

Fixed via https://github.com/react-static/react-static/pull/1283/commits/7c244e45dbdbf8dd12cc4c09ad412253db869cf2

**Pull request closed without merging**
