### PR TITLE
Update fork-ts-checker-webpack-plugin to latest version

### PR DESCRIPTION
**Pull request by deiga**
## Description

- Update plugin version to latest
- Upgrade plugin configuration
- This is a breaking change, if users are using anything less than: Node.js 10, Webpack 4, TypeScript 2.7

## Motivation and Context

- Keeping up-to-date with package versions
- Remove dependency on chokidar 2

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have updated the documentation accordingly
- [ ] I have updated the CHANGELOG with a summary of my changes
- [ ] My changes have tests around them: Tested by building our prod site with this change

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Does this fix the build?

**Comment by deiga** [comment]
> Does this fix the build?

That I didn't test yet, the motivation was separate from that 😄 But I will test that soon

**Comment by SleeplessByte** [comment]
@deiga did you have time to check if this fixed the build? If yes, hopefully we can merge this and #1531 and do an npm release 🗡️

**Comment by jeremy-hanna** [comment]
@SleeplessByte I was able to get this to build with these changes building a new site from the template 

```
$ yarn install --force && yarn build
$ ./packages/react-static/bin/react-static create

  ? What should we name this project? my-static-site
  ? Select a template below... typescript
  Creating new react-static project...

$ cd my-static-site && yarn build

  ...

  Done in 27.22s.
```

Additionally pulling the `tsconfigPath` from a passed in options value instead of [the relative default](https://github.com/react-static/react-static/pull/1540/files#diff-7abb09830a193ea43c9d216159d00b66e2e5bba6b1e33a9f40b4a00f9e3056b4R13) used let me build this from my local build using `yarn link` as well

I can also confirm it fixes the error seen https://github.com/react-static/react-static/pull/1540/files#diff-7abb09830a193ea43c9d216159d00b66e2e5bba6b1e33a9f40b4a00f9e3056b4R13 in the other branch as I ran into that as well

I think this is safe to merge :+1:

**Comment by SleeplessByte** [comment]
Wonderful news. Let's do this.

**Pull request merged**
