### PR TITLE
Upgrade react-helmet to 6.1.0

### PR DESCRIPTION
**Pull request by deiga**
## Description

Upgrade React Helmet to newest version

## Changes/Tasks

- [x] Update version in package.json
- [x] Update yarn.lock

## Motivation and Context

It fixes an issue with warnings for NullComponent

## Types of changes

- [ ] Refactoring/add tests (refactoring or adding test which isn't a fix or add a feature)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have updated the documentation accordingly
- [x] I have updated the CHANGELOG with a summary of my changes
- [ ] My changes have tests around them

### CODE REVIEW

**Review by SleeplessByte — APPROVED** [review]
Thanks! Have you also tried a production build, just to be certain?

**Comment by deiga** [comment]
We only tried upgrading react-helmet straight away, not using upgraded react-static. I can try and get that done as well

**Comment by SleeplessByte** [comment]
Please do. If it works, I'll merge this.

**Comment by deiga** [comment]
@SleeplessByte There appears to be an error with the build process, but it doesn't look like it comes from the Helmet upgrade.
```
Bundling App...
  Error: Trace: TypeError: Cannot read property 'constructor' of undefined
      at new ForkTsCheckerWebpackPlugin (/foo/node_modules/fork-ts-checker-webpack-plugin/src/index.ts:178:29)
      at getTypecheckPlugin (/react-static/packages/react-static-plugin-typescript/node.api.js:116:10)
      at hook (/react-static/packages/react-static-plugin-typescript/node.api.js:62:20)
      at reduce (/react-static/packages/react-static/src/browser/utils/index.js:156:22)
      at Array.reduce (<anonymous>)
      at /react-static/packages/react-static/src/browser/utils/index.js:155:13
      at Object.plugins (../../src/static/plugins.js:67:12)
      at makeWebpackConfig (../../../src/static/webpack/makeWebpackConfig.js:28:19)
      at _callee3$ (../../../src/static/webpack/buildProductionBundles.js:16:11)
      at tryCatch (/react-static/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (/react-static/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (/react-static/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (/react-static/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (/react-static/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at /react-static/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
      at new Promise (<anonymous>)
      at /react-static/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
      at _buildProductionBundles (/react-static/packages/react-static/lib/static/webpack/buildProductionBundles.js:198:34)
      at buildProductionBundles (/react-static/packages/react-static/lib/static/webpack/buildProductionBundles.js:65:34)
      at _callee$ (../../src/commands/bundle.js:36:17)
      at tryCatch (/react-static/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (/react-static/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (/react-static/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (/react-static/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (/react-static/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at /react-static/packages/react-static/bin/react-static:6:11
```

**Comment by SleeplessByte** [comment]
No, that doesn't look like this caused it :( 

You can try to upgrade the `ForkTsCheckerWebpackPlugin`; turn it off, to see if that gets a build going (it's failing in the `react-static-plugin-typescript` plugin). This worked perfectly fine without changes, so I don't quite know what happened. 

Don't fiddle with it for too long. If you can't figure it out I or someone from my team will try to solve it.

**Comment by deiga** [comment]
Yeah, upgrading or disabling the typescript plugin "works" as in, leads to a new error:
```
Importing directory routes from: /foo/src/pages/**/*.{js,jsx}
  TypeError: anymatch is not a function

  - index.js:770 FSWatcher._isIgnored
    [foo]/[chokidar]/index.js:770:25

  - fsevents-handler.js:457 FsEventsHandler._addToFsEvents
    [foo]/[chokidar]/lib/fsevents-handler.js:457:18
```

**Comment by SleeplessByte** [comment]
@deiga can you rebase this?

**Comment by deiga** [comment]
@SleeplessByte done!

**Comment by SleeplessByte** [comment]
This was also included in 7.5.0

**Pull request merged**
